name: IContas CD - Main

on:
  release:
    types: [published]

jobs:
  build-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Configurando Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build da aplicação com application-test
      run: mvn -B clean package -Ptest
    - name: Build da aplicação com application-prod
      run: mvn -B clean package -DskipTests -Pprod
    - name: Build & push da imagem docker
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: thalestakao/icontas
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}