name: IContas CI - Todas branches exceto main

on:
  push:
    branches-ignore:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Configurando Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build da aplicação com application-test.properties
      run: mvn -B clean package -Ptest